# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArrayTypeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArrayTypeDialog(object):
    def setupUi(self, ArrayTypeDialog):
        ArrayTypeDialog.setObjectName("ArrayTypeDialog")
        ArrayTypeDialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(ArrayTypeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.element_type_label = QtWidgets.QLabel(ArrayTypeDialog)
        self.element_type_label.setObjectName("element_type_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.element_type_label)
        self.type_combo = QtWidgets.QComboBox(ArrayTypeDialog)
        self.type_combo.setObjectName("type_combo")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.type_combo)
        self.array_size_label = QtWidgets.QLabel(ArrayTypeDialog)
        self.array_size_label.setObjectName("array_size_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.array_size_label)
        self.size_spin = QtWidgets.QSpinBox(ArrayTypeDialog)
        self.size_spin.setMinimum(1)
        self.size_spin.setMaximum(10000)
        self.size_spin.setProperty("value", 1)
        self.size_spin.setObjectName("size_spin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.size_spin)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(ArrayTypeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ArrayTypeDialog)
        self.buttonBox.accepted.connect(ArrayTypeDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ArrayTypeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ArrayTypeDialog)

    def retranslateUi(self, ArrayTypeDialog):
        _translate = QtCore.QCoreApplication.translate
        ArrayTypeDialog.setWindowTitle(_translate("ArrayTypeDialog", "Array Type Definition"))
        self.element_type_label.setText(_translate("ArrayTypeDialog", "Element Type:"))
        self.type_combo.setItemText(0, _translate("ArrayTypeDialog", "bool_t"))
        self.type_combo.setItemText(1, _translate("ArrayTypeDialog", "uint8"))
        self.type_combo.setItemText(2, _translate("ArrayTypeDialog", "uint16"))
        self.type_combo.setItemText(3, _translate("ArrayTypeDialog", "uint32"))
        self.type_combo.setItemText(4, _translate("ArrayTypeDialog", "uint64"))
        self.type_combo.setItemText(5, _translate("ArrayTypeDialog", "sint8"))
        self.type_combo.setItemText(6, _translate("ArrayTypeDialog", "sint16"))
        self.type_combo.setItemText(7, _translate("ArrayTypeDialog", "sint32"))
        self.type_combo.setItemText(8, _translate("ArrayTypeDialog", "sint64"))
        self.type_combo.setItemText(9, _translate("ArrayTypeDialog", "char_t"))
        self.type_combo.setItemText(10, _translate("ArrayTypeDialog", "float32"))
        self.type_combo.setItemText(11, _translate("ArrayTypeDialog", "float64"))
        self.array_size_label.setText(_translate("ArrayTypeDialog", "Array Size:"))
