# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StructFieldDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StructFieldDialog(object):
    def setupUi(self, StructFieldDialog):
        StructFieldDialog.setObjectName("StructFieldDialog")
        StructFieldDialog.resize(400, 250)
        self.main_layout = QtWidgets.QVBoxLayout(StructFieldDialog)
        self.main_layout.setObjectName("main_layout")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setObjectName("form_layout")
        self.name_label = QtWidgets.QLabel(StructFieldDialog)
        self.name_label.setObjectName("name_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_edit = QtWidgets.QLineEdit(StructFieldDialog)
        self.name_edit.setObjectName("name_edit")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_edit)
        self.main_layout.addLayout(self.form_layout)
        self.type_group = QtWidgets.QGroupBox(StructFieldDialog)
        self.type_group.setObjectName("type_group")
        self.type_layout = QtWidgets.QVBoxLayout(self.type_group)
        self.type_layout.setObjectName("type_layout")
        self.radio_layout = QtWidgets.QHBoxLayout()
        self.radio_layout.setObjectName("radio_layout")
        self.basic_radio = QtWidgets.QRadioButton(self.type_group)
        self.basic_radio.setChecked(True)
        self.basic_radio.setObjectName("basic_radio")
        self.radio_layout.addWidget(self.basic_radio)
        self.array_radio = QtWidgets.QRadioButton(self.type_group)
        self.array_radio.setObjectName("array_radio")
        self.radio_layout.addWidget(self.array_radio)
        self.type_layout.addLayout(self.radio_layout)
        self.type_selection_layout = QtWidgets.QHBoxLayout()
        self.type_selection_layout.setObjectName("type_selection_layout")
        self.type_combo = QtWidgets.QComboBox(self.type_group)
        self.type_combo.setObjectName("type_combo")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_selection_layout.addWidget(self.type_combo)
        self.type_layout.addLayout(self.type_selection_layout)
        self.array_layout = QtWidgets.QHBoxLayout()
        self.array_layout.setObjectName("array_layout")
        self.array_type_label = QtWidgets.QLabel(self.type_group)
        self.array_type_label.setVisible(False)
        self.array_type_label.setObjectName("array_type_label")
        self.array_layout.addWidget(self.array_type_label)
        self.array_display = QtWidgets.QLineEdit(self.type_group)
        self.array_display.setReadOnly(True)
        self.array_display.setVisible(False)
        self.array_display.setObjectName("array_display")
        self.array_layout.addWidget(self.array_display)
        self.configure_array_button = QtWidgets.QPushButton(self.type_group)
        self.configure_array_button.setVisible(False)
        self.configure_array_button.setObjectName("configure_array_button")
        self.array_layout.addWidget(self.configure_array_button)
        self.type_layout.addLayout(self.array_layout)
        self.main_layout.addWidget(self.type_group)
        self.description_layout = QtWidgets.QFormLayout()
        self.description_layout.setObjectName("description_layout")
        self.description_label = QtWidgets.QLabel(StructFieldDialog)
        self.description_label.setObjectName("description_label")
        self.description_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.description_label)
        self.description_edit = QtWidgets.QLineEdit(StructFieldDialog)
        self.description_edit.setObjectName("description_edit")
        self.description_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.description_edit)
        self.main_layout.addLayout(self.description_layout)
        self.buttonBox = QtWidgets.QDialogButtonBox(StructFieldDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.main_layout.addWidget(self.buttonBox)

        self.retranslateUi(StructFieldDialog)
        self.buttonBox.accepted.connect(StructFieldDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(StructFieldDialog.reject) # type: ignore
        self.array_radio.toggled['bool'].connect(self.array_type_label.setVisible) # type: ignore
        self.array_radio.toggled['bool'].connect(self.array_display.setVisible) # type: ignore
        self.array_radio.toggled['bool'].connect(self.configure_array_button.setVisible) # type: ignore
        self.array_radio.toggled['bool'].connect(self.type_combo.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StructFieldDialog)

    def retranslateUi(self, StructFieldDialog):
        _translate = QtCore.QCoreApplication.translate
        StructFieldDialog.setWindowTitle(_translate("StructFieldDialog", "Structure Field"))
        self.name_label.setText(_translate("StructFieldDialog", "Field Name:"))
        self.type_group.setTitle(_translate("StructFieldDialog", "Field Type"))
        self.basic_radio.setText(_translate("StructFieldDialog", "Basic Type"))
        self.array_radio.setText(_translate("StructFieldDialog", "Array Type"))
        self.type_combo.setItemText(0, _translate("StructFieldDialog", "bool_t"))
        self.type_combo.setItemText(1, _translate("StructFieldDialog", "uint8"))
        self.type_combo.setItemText(2, _translate("StructFieldDialog", "uint16"))
        self.type_combo.setItemText(3, _translate("StructFieldDialog", "uint32"))
        self.type_combo.setItemText(4, _translate("StructFieldDialog", "uint64"))
        self.type_combo.setItemText(5, _translate("StructFieldDialog", "sint8"))
        self.type_combo.setItemText(6, _translate("StructFieldDialog", "sint16"))
        self.type_combo.setItemText(7, _translate("StructFieldDialog", "sint32"))
        self.type_combo.setItemText(8, _translate("StructFieldDialog", "sint64"))
        self.type_combo.setItemText(9, _translate("StructFieldDialog", "char_t"))
        self.type_combo.setItemText(10, _translate("StructFieldDialog", "float32"))
        self.type_combo.setItemText(11, _translate("StructFieldDialog", "float64"))
        self.array_type_label.setText(_translate("StructFieldDialog", "Array of:"))
        self.configure_array_button.setText(_translate("StructFieldDialog", "Configure..."))
        self.description_label.setText(_translate("StructFieldDialog", "Description:"))
